### ISSUE TITLE
Add a detailed beacon chain documentation

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-docs#15]
### Solution

Add a detailed beacon chain documentation. Once done review it with @nilesh-uniris @I-archer-zero @samuel-uniris 

- [ ] Beacon Chains (Introduction + Need for beacon chains in AE Blockchain)
- [ ] How is AE implementing the Beacons Chains
- [ ] Advantages and Future Scope of Beacons Chains

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-docs/15?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
