### ISSUE TITLE
Detailed Testnet Documentation

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-docs#16]
### Solution

Please add a detailed testnet documentation. Once done, get it reviewed by @nilesh-uniris @i

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-docs/16?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
