### ISSUE TITLE
Full Documentation Review and Enhancement Suggestions

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-docs#25]
https://archethic-foundation.github.io/archethic-docs/

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-docs/25?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-docs/25?planning-poker) with ZenHub @lucy-sha512

**Comment by lucy-sha512** [comment]
### Description
This issue refers to the documentation at [https://archethic-foundation.github.io/archethic-docs/](url) and reviews it for further enhancement.
The documentation has two categories:

- Learn: Talks about the innovations in Archethic blockchain like ARCH consensus, hybrid root of trust, decentralized identitities etc.
- Build : t aims to provide information about usage to build new decentralized applications on top of Archethic.
