### ISSUE TITLE
AEWeb  - Add a section "How to transfer your website to AEWeb"

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-docs#42]
### Describe the solution you'd like

Add a section in the documentation titled "How to transfer your website to AEWeb" with examples featuring the most popular web hosting platforms.

**Comment by samuelmanzanera** [comment]
Proposed hosting providers: 
- [ ] Gandi
- [ ] Cloudfare
- [ ] OVH
- [ ] GoDaddy
